#! /bin/sh

#Autostart Keybindings, Panel, Background, External Monitor
sxhkd &
panel &
feh --bg-fill ~/.wallpaper.jpg &
xrandr --output LVDS1 --primary
xrandr --output HDMI1 --mode 1920x1080 --right-of LVDS1
bspc config -m ^1 top_padding 15

#Main Config
bspc monitor -f primary
bspc config border_width         2
bspc config window_gap          12
bspc config top_padding         15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

if (xrandr | grep "HDMI1 connected" > /dev/null)
  xrandr --output HDMI1 --mode 1920x1080 --right-of LVDS1
  bspc monitor HDMI1 -d web music docs
  bspc monitor LVDS1 -d dev misc
else
  bspc wm -r HDMI1
  bspc monitor LVDS1 -d dev web music docs misc
fi

#Check to see if monitor is there every 10 minutes
while [ true ]
do
  if (xrandr | grep "HDMI1 connected" > /dev/null)
    xrandr --output HDMI1 --mode 1920x1080 --right-of LVDS1
    bspc monitor HDMI1 -d web music docs
    bspc monitor LVDS1 -d dev misc
  else
    bspc wm -r HDMI1
    bspc monitor LVDS1 -d dev web music docs misc
  fi
  sleep 10m
done
