#! /bin/sh

bspc monitor eDP-1 -d dev misc web music docs

#Program Rules
bspc rule -a "chromium" desktop=^3
bspc rule -a "spotify" desktop=^4

#Main Config
bspc monitor -f primary
bspc config border_width         4
bspc config window_gap          15
bspc config top_padding         35

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

#Wallpaper
feh --bg-fill ~/.wallpaper.jpg &

#Start up the bar
#Note lemonbar is the xft patch version from the AUR
~/.config/bspwm/panel|lemonbar -g 3840x30 -p -F "#d0d0d0" -B "#3a3a3a" -f mononoki-Regular:size=18 &
sxhkd &
chromium --force-device-scale-factor=2 &
spotify  --force-device-scale-factor=2 &
urxvt &
