#!/usr/bin/bash

#Define the battery
Battery() {
  echo $(acpi --battery | tail -n 1 | cut -d, -f2)
}
Date() {
	date | awk '{print $1 " " $2 " " $3 " " $4 }'
}

DiskUsage() {
  df -m | grep /dev/sda1 | awk '{print $5}'
}

Desktops() {
  QUERY=$(bspc query -D | sed ':a;N;$!ba;s/\n/  /g')
  ACTIVE=$(bspc query --desktops --desktop focused)
  printf " %s " "$QUERY" | sed -e "s/ $ACTIVE /%{F#3a3a3a}%{B#d0d0d0} $ACTIVE %{F-}%{B-}/"
}


# Print the percentage
while true; do
  echo "%{l} $(Desktops)%{c}$(Date)%{r}Disk: $(DiskUsage) Batt: $(Battery)"
        sleep 0.01;
done
